const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let data;
const statuses=['new','in-progress','waiting-on-employee','waiting-on-provider','resolved','closed'];
const label=s=>s.replaceAll('-',' ');
async function api(path,body){const r=await fetch('/api/care/admin'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(d.error||'Unable to load');return d}
async function load(){try{data=await api('');$('#identity').textContent='Signed in as '+data.leader;$('#notice').textContent=data.ready?'Email-first routing is connected. “Accepted” means the email provider accepted the notification; it does not prove delivery or that a leader read it.':'Setup needed: connect an email sender and confirm leader recipients. Employee request submission is disabled until routing is ready. Direct provider contacts and uniform email drafts still work.';render()}catch(e){$('#notice').textContent=e.message}}
function render(){document.querySelector("#pilot-state").textContent="AI: "+(data.aiReady?"configured; test below":"awaiting Groq setup")+" · Email: "+(data.ready?"connected":"awaiting sender setup");let total=0,open=0,fresh=0;for(const x of data.counts){total+=x.total;if(!['resolved','closed'].includes(x.status))open+=x.total;if(x.status==='new')fresh=x.total}$('#metrics').innerHTML=[['Open',open],['New',fresh],['All requests',total]].map(([a,b])=>`<div class="metric">${a}<strong>${b}</strong></div>`).join('');let filter=$('#filter').value;const rows=data.rows.filter(x=>filter==='all'||(filter==='open'?!['resolved','closed'].includes(x.status):x.status===filter));$('#requests').innerHTML=rows.length?rows.map(x=>`<details class="request-row"><summary>${x.is_test?"[TEST] ":""}${esc(x.name)} · ${esc(label(x.topic))} · ${esc(label(x.status))}</summary><p>Request ${esc(x.id)}<br>Created ${esc(new Date(x.created).toLocaleString())}<br>Timing: ${esc(x.timing)}<br>Contact: ${esc(x.contact)}</p><div class="summary">${esc(x.details||'No additional details.')}</div><p>Email: <strong>${esc(x.email_state)}</strong> · ${esc(JSON.parse(x.email_to).join(', '))}</p><form data-id="${esc(x.id)}" data-revision="${x.revision}"><label>Status<select name="status">${statuses.map(s=>`<option value="${s}" ${s===x.status?'selected':''}>${label(s)}</option>`).join('')}</select></label><label>Owner<select name="owner"><option value="">Unassigned</option>${data.leaders.map(s=>`<option ${s===x.owner?'selected':''}>${esc(s)}</option>`).join('')}</select></label><button class="primary">Save update</button></form>${['failed','pending'].includes(x.email_state)?`<button class="secondary" data-retry="${esc(x.id)}">Retry email notification</button>`:''}${x.email_state==='needs-review'?'<p>Notification needs manual review. Check the mailbox/provider before sending again.</p>':''}<p class="row-message" role="status"></p></details>`).join(''):'<p class="empty-state">No requests in this view. Use Create practice request to test the workflow.</p>';$('#usage').innerHTML=data.usage.length?'<ul>'+data.usage.map(x=>`<li>${esc({'/index.html':'Home','/uniforms.html':'Uniform catalog','/benefits.html':'Resource directory'}[x.page]||x.page)}: ${x.views} views</li>`).join('')+'</ul>':'<p>No page views recorded yet.</p>'}
$('#filter').onchange=()=>data&&render();$('#refresh').onclick=load;
$('#requests').addEventListener('submit',async e=>{e.preventDefault();const f=e.target,b=f.querySelector('button');b.disabled=true;try{await api('/update',{...Object.fromEntries(new FormData(f)),id:f.dataset.id,revision:Number(f.dataset.revision)});await load()}catch(err){f.closest('details').querySelector('.row-message').textContent=err.message}finally{b.disabled=false}});
$('#requests').addEventListener('click',async e=>{const b=e.target.closest('[data-retry]');if(!b)return;b.disabled=true;try{await api('/retry',{id:b.dataset.retry});await load()}catch(err){b.closest('details').querySelector('.row-message').textContent=err.message}finally{b.disabled=false}});load();

for(const [id,path] of [['practice','/test'],['clear-practice','/clear-tests']])document.getElementById(id).onclick=async()=>{const b=document.getElementById(id);b.disabled=true;try{await api(path,{});document.getElementById('practice-message').textContent=id==='practice'?'Practice request ready below. No email sent.':'Practice requests cleared.';await load()}catch(e){document.getElementById('practice-message').textContent=e.message}finally{b.disabled=false}};

document.getElementById('check-ai').onclick=async()=>{const b=document.getElementById('check-ai');b.disabled=true;try{const r=await fetch('/api/care/assist',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:'I need childcare that fits an early shift',consent:true})});const d=await r.json();document.getElementById('practice-message').textContent=d.mode==='groq'?'Groq responded with an approved resource category.':'Groq is not responding yet; local topic matching is available.'}catch{document.getElementById('practice-message').textContent='Could not check AI. Direct resources remain available.'}finally{b.disabled=false}};
