const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const items=[
{id:'polo',name:'Shae polo',group:'Tops',colors:['Red','Navy'],type:'shirt',image:'polo'},
{id:'leader',name:'Lenexa leader polo',group:'Tops',colors:['Blue'],type:'shirt',image:'leader'},
{id:'chef',name:'Chef coat',group:'Tops',colors:['Navy','Red'],type:'shirt',image:'chef'},
{id:'pants',name:'Uniform pants',group:'Bottoms',colors:['Midnight navy'],type:'pants',image:'pants'},
{id:'hat',name:'Flagger hat',group:'Accessories',colors:['Navy'],type:'accessory',image:'hat'},
{id:'nametag',name:'Name tag',group:'Accessories',colors:['Standard'],type:'accessory',image:'nametag'},
{id:'belt',name:'Taylors belt',group:'Accessories',colors:['Red','Navy'],type:'belt',image:'belt'},
{id:'jacket',name:'Bluemond softshell jacket',group:'Outerwear',colors:['Red','Navy'],type:'shirt',image:'jacket'}];
let basket=[];let emailBody='';let onlineReady=false;let uniformSubmission;
fetch('/api/care/config').then(r=>r.json()).then(d=>onlineReady=d.ready).catch(()=>{});
const opts=a=>a.map(x=>`<option>${esc(x)}</option>`).join('');
function render(){const category=$('#category').value;$('#catalog').innerHTML=items.filter(x=>category==='all'||x.group===category).map(x=>`<article class="product"><div class="product-photo">${x.image?`<img src="uniform-images/${x.image}.jpg" alt="Reference photo for ${esc(x.name)}" loading="lazy">`:`<div class="text-product"><span>${x.group}</span><strong>${x.name}</strong><small>Photo coming with approved catalog</small></div>`}</div><div class="product-body"><span class="eyebrow">${x.group}</span><h3>${x.name}</h3><p class="price">Price confirmed by team</p><form data-item="${x.id}"><div class="two"><label class="field">Color<select name="color">${opts(x.colors)}</select></label><label class="field">Quantity<input name="qty" type="number" min="1" max="10" value="1" required></label></div>${x.type==='shirt'?`<div class="two"><label class="field">Fit<select name="fit">${opts(['Men’s','Women’s','Help me choose'])}</select></label><label class="field">Size<select name="size">${opts(['XS','S','M','L','XL','2XL','3XL','4XL','5XL','6XL','Help me choose'])}</select></label></div>`:x.type==='pants'?`<label class="field">Fit<select name="fit">${opts(['Men’s','Women’s','Help me choose'])}</select></label><div class="two"><label class="field">Waist / size<input name="size" required maxlength="25" placeholder="e.g. 32 or size 8"></label><label class="field">Inseam<input name="inseam" required maxlength="25" placeholder="e.g. 30"></label></div>`:`<label class="field">${x.id==='nametag'?'Name to print':x.type==='belt'?'Belt size':'Size / fit'}<input name="size" required maxlength="60" ${x.id==='hat'?'value="Adjustable"':''} placeholder="${x.id==='nametag'?'Your preferred name':'Size or help me choose'}"></label>`}<button class="secondary">Add to request</button><span class="added" role="status"></span></form></div></article>`).join('')}
function renderBasket(){$('#count').textContent=basket.reduce((a,x)=>a+x.qty,0);$('#basket').innerHTML=basket.length?basket.map((x,i)=>`<div class="basket-row"><div><strong>${x.qty} × ${esc(x.name)}</strong><small>${esc(x.color)} · ${esc(x.fit||'')}${x.fit?' · ':''}${esc(x.size)}${x.inseam?' · inseam '+esc(x.inseam):''}</small></div><button type="button" data-remove="${i}" aria-label="Remove ${esc(x.name)}">×</button></div>`).join(''):'<div class="basket-empty">Your request is empty.<br><small>Add an item from the catalog to get started.</small></div>';$('#review-request').disabled=!basket.length}
$('#category').onchange=render;
$('#catalog').addEventListener('submit',e=>{e.preventDefault();const f=e.target,d=Object.fromEntries(new FormData(f)),item=items.find(x=>x.id===f.dataset.item);if(!d.size.trim()||(item.type==='pants'&&!d.inseam.trim())){f.querySelector('.added').textContent='Enter a size or ask for help choosing.';return}if(basket.length>=12){f.querySelector('.added').textContent='Review your 12 items before adding more.';return}basket.push({...d,qty:Number(d.qty),name:item.name});renderBasket();f.querySelector('.added').textContent='Added to your request';});
$('#basket').onclick=e=>{const b=e.target.closest('[data-remove]');if(b){basket.splice(Number(b.dataset.remove),1);renderBasket()}};
$('#request-form').onsubmit=e=>{e.preventDefault();if(!basket.length)return;const d=Object.fromEntries(new FormData(e.target));if(!d.employee.trim()){$('#form-status').textContent='Please enter your name.';return}emailBody=`Uniform request — Chick-fil-A Hueytown #06123\n\nEmployee: ${d.employee.trim()}\nArea: ${d.area}\nRole: ${d.role}\nReason: ${d.reason}\nNeeded by: ${d.needed||'Not specified'}\n\n${basket.map(x=>`${x.qty} × ${x.name} | ${x.color} | ${x.fit||''} ${x.size}${x.inseam?' | inseam '+x.inseam:''}`).join('\n')}\n\nNotes: ${d.notes.trim()||'None'}\n\nPlease confirm approved styles, availability, any cost, and pickup timing before ordering. No payment or payroll deduction is authorized by this request.`;uniformSubmission={id:crypto.randomUUID(),name:d.employee.trim(),topic:'uniform',timing:d.needed||'Not specified',details:emailBody};$('#review-content').innerHTML=`<div class="eyebrow">REVIEW BEFORE SENDING</div><h2>Ready for your team</h2><p>To: Hueytown uniform team<br><strong>06123@chick-fil-a.com</strong></p><div class="summary">${esc(emailBody)}</div><p>Your email app will open with this request. Press Send there to deliver it. If you do not have an email app, copy or download the request and give it to your restaurant leader. The portal does not save requests or confirm delivery.</p><a class="primary" href="mailto:06123@chick-fil-a.com?subject=${encodeURIComponent('[UNIFORM REQUEST] '+d.employee.trim()+' — Hueytown')}&body=${encodeURIComponent(emailBody)}">Open request email</a><button class="secondary" id="copy">Copy request text</button><button class="secondary" id="download-request">Download request</button><p id="copy-status" role="status"></p>`;if(onlineReady)$('#review-content').insertAdjacentHTML('beforeend','<form id="save-uniform"><h3>Or send through Team Care</h3><p>Choose this route instead of sending a separate email. It saves the request for leaders and sends an email notification.</p><label class="field">Your email or phone<input name="contact" required maxlength="120"></label><label class="consent-check"><input type="checkbox" name="consent" required>I agree to share this request with approved Team Care leaders and the uniform team.</label><button class="primary">Send and save request</button><p role="status" id="online-status"></p></form>');$('#review-dialog').showModal()};
$('#review-dialog .close').onclick=()=>$('#review-dialog').close();$('#review-dialog').onclick=async e=>{if(e.target===$('#review-dialog'))$('#review-dialog').close();if(e.target.id==='copy'){try{await navigator.clipboard.writeText(emailBody);$('#copy-status').textContent='Copied. Paste into an email to 06123@chick-fil-a.com and send.'}catch{$('#copy-status').textContent='Select the request text above to copy it manually.'}}};render();renderBasket();

document.querySelector('#review-dialog').addEventListener('click',e=>{if(e.target.id!=='download-request')return;const url=URL.createObjectURL(new Blob(['To: 06123@chick-fil-a.com\n\n'+emailBody],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='Hueytown-uniform-request.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});

document.querySelector('#review-dialog').addEventListener('submit',async e=>{if(e.target.id!=='save-uniform')return;e.preventDefault();const f=e.target,b=f.querySelector('button'),message=f.querySelector('[role=status]');b.disabled=true;try{const r=await fetch('/api/care/requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...uniformSubmission,contact:f.elements.contact.value,consent:f.elements.consent.checked})});const d=await r.json();if(!r.ok)throw Error(d.error);message.textContent='Saved: '+d.id+'. '+(d.emailState==='accepted'?'Email notification accepted by the provider. Do not send a duplicate email.':'Email notification is not confirmed. Contact your leader with this reference.');b.textContent='Request saved'}catch(err){message.textContent=err.message;b.disabled=false}});
